package github.KingVampyre.DeepTrenches.core.init.block;

import github.KingVampyre.DeepTrenches.core.block.entity.CustomSignBlockEntity;
import github.KingVampyre.DeepTrenches.core.block.entity.StaspNestBlockEntity;
import github.KingVampyre.DeepTrenches.core.init.block.DTBlocks;
import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.util.registry.Registry;

import static github.KingVampyre.DeepTrenches.core.init.block.DTBlocks.*;
import static net.minecraft.util.registry.Registry.BLOCK_ENTITY_TYPE;

public class DTBlockEntityTypes {

	public static final BlockEntityType<CustomSignBlockEntity> SIGN;
	  public static final BlockEntityType<StaspNestBlockEntity> STASP_NEST;

	static {
		SIGN = FabricBlockEntityTypeBuilder.create(
				CustomSignBlockEntity::new,
				ALMOND_SIGN, ALMOND_WALL_SIGN,
				ANAMEATA_SIGN, ANAMEATA_WALL_SIGN,
				ANGELS_TRUMPET_SIGN, ANGELS_TRUMPET_WALL_SIGN,
				AQUEAN_SIGN, AQUEAN_WALL_SIGN,
				BARSHROOKLE_SIGN, BARSHROOKLE_WALL_SIGN,
				BLACK_BIRCH_SIGN, BLACK_BIRCH_WALL_SIGN,
				BLUE_MAHOE_SIGN, BLUE_MAHOE_WALL_SIGN,
				BLUE_SPRUCE_SIGN, BLUE_SPRUCE_WALL_SIGN,
				BOTTLEBRUSH_SIGN, BOTTLEBRUSH_WALL_SIGN,
				BROMYA_SIGN, BROMYA_WALL_SIGN,
				BUBBLETREE_SIGN, BUBBLETREE_WALL_SIGN,
				CALCEARB_SIGN, CALCEARB_WALL_SIGN,
				CHERRY_SIGN, CHERRY_WALL_SIGN,
				CHOTORN_SIGN, CHOTORN_WALL_SIGN,
				COOK_PINE_SIGN, COOK_PINE_WALL_SIGN,
				CROLOOD_SIGN, CROLOOD_WALL_SIGN,
				DARK_CROLOOD_SIGN, DARK_CROLOOD_WALL_SIGN,
				DARK_FUCHSITRA_SIGN, DARK_FUCHSITRA_WALL_SIGN,
				DARK_RED_ELM_SIGN, DARK_RED_ELM_WALL_SIGN,
				DEAD_WART_TREE_SIGN, DEAD_WART_TREE_WALL_SIGN,
				DRIGYUS_SIGN, DRIGYUS_WALL_SIGN,
				EBONY_SIGN, EBONY_WALL_SIGN,
				ENDERHEART_SIGN, ENDERHEART_WALL_SIGN,
				FLALM_SIGN, FLALM_WALL_SIGN,
				FRUCE_SIGN, FRUCE_WALL_SIGN,
				FUCHSITRA_SIGN, FUCHSITRA_WALL_SIGN,
				FUGMOS_SIGN, FUGMOS_WALL_SIGN,
				FUNERANITE_SIGN, FUNERANITE_WALL_SIGN,
				GHOSHROOM_SIGN, GHOSHROOM_WALL_SIGN,
				GIANT_VIOLET_SIGN, GIANT_VIOLET_WALL_SIGN,
				GUAIACUM_SIGN, GUAIACUM_WALL_SIGN,
				JOSHUA_SIGN, JOSHUA_WALL_SIGN,
				KLINKII_PINE_SIGN, KLINKII_PINE_WALL_SIGN,
				MELALEUCA_SIGN, MELALEUCA_WALL_SIGN,
				MURKANTUAN_SIGN, MURKANTUAN_WALL_SIGN,
				NORFOLK_PINE_SIGN, NORFOLK_PINE_SIGN,
				OBSCRUS_SIGN, OBSCRUS_WALL_SIGN,
				ORHPRIS_SIGN, ORHPRIS_WALL_SIGN,
				PELTOGYNE_SIGN, PELTOGYNE_WALL_SIGN,
				PIN_CHERRY_SIGN, PIN_CHERRY_WALL_SIGN,
				PLUM_SIGN, PLUM_WALL_SIGN,
				PURFUNGA_SIGN, PURFUNGA_WALL_SIGN,
				RARK_SIGN, RARK_WALL_SIGN,
				RED_ELM_SIGN, RED_ELM_WALL_SIGN,
				RHADI_SIGN, RHADI_WALL_SIGN,
				SANGUART_SIGN, SANGUART_WALL_SIGN,
				SCARLET_THIORCEN_SIGN, SCARLET_THIORCEN_WALL_SIGN,
				SEQUOIA_SIGN, SEQUOIA_WALL_SIGN,
				SPROOM_SIGN, SPROOM_WALL_SIGN,
				STORTREEAN_SIGN, STORTREEAN_WALL_SIGN,
				STROOMEAN_SIGN, STROOMEAN_WALL_SIGN,
				SUNRISE_FUNGUS_SIGN, SUNRISE_FUNGUS_WALL_SIGN,
				TARK_SIGN, TARK_WALL_SIGN,
				TEAK_SIGN, TEAK_WALL_SIGN,
				THUNDERCLOUD_PLUM_SIGN, THUNDERCLOUD_PLUM_WALL_SIGN,
				VYNHERT_SIGN, VYNHERT_WALL_SIGN,
				WART_TREE_SIGN, WART_TREE_WALL_SIGN,
				WENGE_SIGN, WENGE_WALL_SIGN,
				YEW_SIGN, YEW_WALL_SIGN
		).build(null);

		STASP_NEST = FabricBlockEntityTypeBuilder.create(StaspNestBlockEntity::new, DTBlocks.STASP_NEST).build(null);
	}

	public static void initialize() {
		Registry.register(BLOCK_ENTITY_TYPE, "deep_trenches:sign", SIGN);
		Registry.register(BLOCK_ENTITY_TYPE, "deep_trenches:stasp_nest", STASP_NEST);
	}

}